name: Build and deploy packege

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build "back/KalleSoft.Extensions/KalleSoft.Extensions.csproj" --configuration Release /property:"Version=2.0.${{ github.run_number }}

    - name: Teste
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "back/KalleSoft.Extensions/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json 
